name: Import users
on:
  push:
    paths:
      - users/**
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_SECRET }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ vars.DEV_SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Checkout
        uses: actions/checkout@v4
          
  importUsers:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_SECRET }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ vars.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create folder
        run: ssh ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }} "rm -rf dataset && mkdir dataset || mkdir dataset"

      - name: Upload users to server
        run: |
          ls -lha
          scp -r scripts ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }}:dataset/
          scp -r uasers ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }}:dataset/
  
      - name: Import admin users
        run: |
          ssh ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }} 'bash -s' <<'ENDSSH'
          set +e
          source .bashrc
          cd dataset/scripts
          chmod +x importAdmins.sh
          ./importAdmins.sh
          ENDSSH

      - name: Import users
        run: |
          ssh ${{ vars.DEV_SSH_USERNAME }}@${{ vars.DEV_SSH_HOST }} 'bash -s' <<'ENDSSH'
          set +e
          source .bashrc
          cd dataset/scripts
          chmod +x importUsers.sh
          ./importUsers.sh
          ENDSSH
